default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        files: ".*"
      - id: check-case-conflict
        files: ".*"
      - id: check-ast
        files: ".*\\.py$"
      - id: check-merge-conflict
        files: ".*"
      - id: check-toml
        files: ".*\\.toml$"
      - id: check-yaml
        files: ".*\\.ya?ml$"
        args: ["--unsafe"]
      - id: debug-statements
        files: "^(src|tests)/.*\\.py$"
      - id: end-of-file-fixer
        files: ".*"
      - id: trailing-whitespace
        files: ".*"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.2
    hooks:
      - id: check-github-workflows
        files: "^\\.github/workflows/.*\\.ya?ml$"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --no-cache]
      - id: ruff-format
